services:
  python:
    build: .
    volumes:
      - .:/app
    env_file:
      # Remote Elasticsearch and data source credentials
      - .docker-compose_elastic_secret.env
      - .docker-compose_source_secret.env
    extra_hosts:
      # For access to remote resources via ssh tunnel on host
      - "host.docker.internal:host-gateway"
