services:
  python:
    build: .
    volumes:
      - .:/app
    network_mode: host

  elastic:
    image: elasticsearch:7.17.19
    # image: elasticsearch:latest
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
  
  kibana:
    image: kibana:7.17.19
    # image: kibana:latest
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200

  solr:
    image: uclalibrary/solr-ursus:7.4
    ports:
      - '127.0.0.1:8983:8983'
