services:
  python:
    build: .
    volumes:
      - .:/app
    extra_hosts:
      # For access to remote resources via ssh tunnel on host
      - "host.docker.internal:host-gateway"

  elastic:
    image: elasticsearch:7.17.19
    # image: elasticsearch:latest
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
  
  kibana:
    image: kibana:7.17.19
    # image: kibana:latest
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200
